// DO NOT EDIT THIS FILE

async function changeLanguage(lang) {
	const response = await fetch('./pageData.json');
	const pageData = await response.json();
	let languageData = pageData[document.getElementsByTagName("body")[0].getAttribute("data-page")][lang]["translation"]
	for (let item in languageData) {
		document.getElementById(item).innerText = languageData[item];
	}
	let globalData = pageData["global"][lang]["translation"]
	console.log(globalData)
	for (let item in globalData) {
		document.getElementById(item).innerText = globalData[item];
	}
	// set cookie for language	
	document.cookie = "lang=" + lang;
}

document.onload = (async () => {
	// get language from cookie
	let lang = document.cookie.split('=')[1];
	if (lang != 'en' && lang != 'vn') {
		lang = 'en';
	}

	// change language
	changeLanguage(lang);

})()