// DO NOT EDIT THIS FILE

const express = require("express")
const app = express()
app.use(express.static("./public/"))
app.use(express.static("./public/pages/"))
app.use(express.static("./public/scripts/"))

app.get("/", (req, res) => {
	res.sendFile(__dirname + "/public/index.html")
})

app.get("/i18n.json", (req, res) => {
	res.sendFile(__dirname + "/i18n.json")
})

app.listen(3000, () => {
	console.log("Listening on port 3000")
})
