// DO NOT EDIT THIS FILE!

async function getHTML(url) {
	const response = await fetch(url);
	return await response.text();
}

document.onload = (async () => {
	const header = await getHTML('./header.html');
	document.getElementsByTagName("nav")[0].innerHTML = header;	
	const footer = await getHTML('./footer.html');
	document.getElementsByClassName("footer")[0].innerHTML = footer;	
})();